[package]
name = "trie-root"
version = "0.11.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "In-memory patricia trie operations"
repository = "https://github.com/paritytech/parity-common"
license = "Apache-2.0"
categories = [ "no-std" ]

[dependencies]
hash-db = { path = "../hash-db", default-features = false, version = "0.11.0"}

[dev-dependencies]
hex-literal = "0.1"
keccak-hasher = { path = "../test-support/keccak-hasher", version = "0.11.0" }
trie-standardmap = { path = "../test-support/trie-standardmap", version = "0.11.0" }
# DISABLE the following line when publishing until cyclic dependencies are resolved https://github.com/rust-lang/cargo/issues/4242
reference-trie = { path = "../test-support/reference-trie", version = "0.11.0" }

[features]
default = ["std"]
std = [
	"hash-db/std"
]
