[package]
name = "trie-bench"
description = "Standard benchmarking suite for tries"
version = "0.19.0"
authors = ["Parity Technologies <admin@parity.io>"]
repository = "https://github.com/paritytech/trie/"
license = "Apache-2.0"
edition = "2018"

[dependencies]
keccak-hasher = { path = "../keccak-hasher", version = "0.15.2" }
trie-standardmap = { path = "../trie-standardmap", version = "0.15.2" }
hash-db = { path = "../../hash-db" , version = "0.15.2"}
memory-db = { path = "../../memory-db", version = "0.18.0" }
trie-root = { path = "../../trie-root", version = "0.15.2" }
trie-db = { path = "../../trie-db", version = "0.19.2" }
criterion = "0.2.8"
parity-scale-codec = { version = "1.0.3" }
